For Each Attribute: (all numeric-valued)
   1. Number of times pregnant
   2. Plasma glucose concentration a 2 hours in an oral glucose tolerance test
   3. Diastolic blood pressure (mm Hg)
   4. Triceps skin fold thickness (mm)
   5. 2-Hour serum insulin (mu U/ml)
   6. Body mass index (weight in kg/(height in m)^2)
   7. Diabetes pedigree function
   8. Age (years)
   9. Class variable (0 or 1)

In [21]:
# first neural network with keras tutorial
from numpy import loadtxt
from keras.models import Sequential
from keras.layers import Dense
import pandas as pd
from sklearn.model_selection import train_test_split

# load the dataset
#dataset = loadtxt('C:/Users/muhzu/PycharmProjects/pima-indians-diabetes-data.csv', delimiter=',')
# split into input (X) and output (y) variables
headerList=['no. of time pregnant','oral glucose','diastolic blood pressure','triceps skin thickness',
                        '2-hours serum insulin','body mass index','diabetes predigree ftn','age','target']
df = pd.read_csv('C:/Users/muhzu/PycharmProjects/pima-indians-diabetes-data.csv',names=headerList)

df.head()
# X = dataset[:,0:8]
# y = dataset[:,8]

,no. of time pregnant,oral glucose,diastolic blood pressure,triceps skin thickness,2-hours serum insulin,body mass index,diabetes predigree ftn,age,target
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1

In [22]:
x = df.drop("target",axis=1)
y = df["target"]

In [20]:
x[:5]

,no. of time pregnant,oral glucose,diastolic blood pressure,triceps skin thickness,2-hours serum insulin,body mass index,diabetes predigree ftn,age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33

In [33]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2,random_state=42)

In [34]:
# define the keras model
model = Sequential()
model.add(Dense(12, input_dim=8, activation='relu'))
model.add(Dense(8, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

In [35]:

# compile the keras model
model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [74]:


# fit the keras model on the dataset
model.fit(X_train, y_train, epochs=20
          , batch_size=10)

Epoch 1/20
614/614 [==============================] - 0s 168us/step - loss: 0.4944 - accuracy: 0.7410
Epoch 2/20
614/614 [==============================] - 0s 133us/step - loss: 0.4896 - accuracy: 0.7492
Epoch 3/20
614/614 [==============================] - 0s 137us/step - loss: 0.4928 - accuracy: 0.7345
Epoch 4/20
614/614 [==============================] - 0s 148us/step - loss: 0.4955 - accuracy: 0.7362
Epoch 5/20
614/614 [==============================] - 0s 135us/step - loss: 0.4947 - accuracy: 0.7443
Epoch 6/20
614/614 [==============================] - 0s 142us/step - loss: 0.4926 - accuracy: 0.7443
Epoch 7/20
614/614 [==============================] - 0s 140us/step - loss: 0.4878 - accuracy: 0.7345
Epoch 8/20
614/614 [==============================] - 0s 140us/step - loss: 0.4954 - accuracy: 0.7313
Epoch 9/20
614/614 [==============================] - 0s 135us/step - loss: 0.4925 - accuracy: 0.7492
Epoch 10/20
614/614 [==============================] - 0s 153us/step - loss: 0.5003 - accuracy: 0.7362
Epoch 11/20
614/614 [==============================] - 0s 150us/step - loss: 0.4899 - accuracy: 0.7443
Epoch 12/20
614/614 [==============================] - 0s 161us/step - loss: 0.4857 - accuracy: 0.7443
Epoch 13/20
614/614 [==============================] - 0s 132us/step - loss: 0.5063 - accuracy: 0.7199
Epoch 14/20
614/614 [==============================] - 0s 160us/step - loss: 0.4914 - accuracy: 0.7313
Epoch 15/20
614/614 [==============================] - 0s 182us/step - loss: 0.4977 - accuracy: 0.7410
Epoch 16/20
614/614 [==============================] - 0s 160us/step - loss: 0.4888 - accuracy: 0.7573
Epoch 17/20
614/614 [==============================] - 0s 135us/step - loss: 0.4847 - accuracy: 0.7410
Epoch 18/20
614/614 [==============================] - 0s 143us/step - loss: 0.4859 - accuracy: 0.7573
Epoch 19/20
614/614 [==============================] - 0s 158us/step - loss: 0.4897 - accuracy: 0.7394
Epoch 20/20
614/614 [==============================] - 0s 153us/step - loss: 0.4977 - accuracy: 0.7329

In [75]:

# evaluate the keras model
loss_of_model, accuracy = model.evaluate(X_test, y_test)
print(f'loss of the model {loss_of_model},Accuracy: %.2f' % (accuracy*100))

154/154 [==============================] - 0s 45us/step
loss of the model 0.5711794302061006,Accuracy: 74.03

In [79]:
# make probability predictions with the model
predictions = model.predict(X_test)
# round predictions
# rounded = [round(X_test[0]) for x in predictions]
# rounded[:10]
predictions[:5]

array([[0.4747328 ],
       [0.22837803],
       [0.30667907],
       [0.22026184],
       [0.45218828]], dtype=float32)

In [90]:
import numpy as np
from sklearn.metrics import classification_report
# make class predictions with the model
predictions_class = model.predict_classes(X_test)
# summarize the first 5 cases
# for i in range(10):
# 	print(f'%d (expected %d){predictions_class[i], y_test[i]}')
my_predict =np.array(predictions_class)
my_predict

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0]])

In [80]:
y_test

668    0
324    0
624    0
690    0
473    0
      ..
355    1
534    0
344    0
296    1
462    0
Name: target, Length: 154, dtype: int64

In [91]:
print(classification_report(y_test,predictions_class))

              precision    recall  f1-score   support

           0       0.76      0.87      0.81        99
           1       0.68      0.51      0.58        55

    accuracy                           0.74       154
   macro avg       0.72      0.69      0.70       154
weighted avg       0.73      0.74      0.73       154